// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://parqckqenpsfqzuwysox.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBhcnFja3FlbnBzZnF6dXd5c294Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2MzkyNTQsImV4cCI6MjA2MDIxNTI1NH0.c23BPGKIGwLk68EifNtoFD4EuMV3cpuieDN6gzI3O_I";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);